version: '3'

services:
  php:
    build: .
    volumes:
      - .:/var/www/html
    expose:
      - 9000

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
